server:
  port: 8002
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5434/shoehome
    username: dbadmin
    password: dl123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect